spring:
  # H2 ?????? ?? ??
  h2:
    console:
      enabled: true  # H2 ?? ???
      path: /h2-console  # H2 ?? ?? ?? (?: http://localhost:8080/h2-console)
      settings:
        trace: false # SQL ?? ???? (??? true? ??)
        web-allow-others: false # ?? ?? ?? ?? (?? ????? false ??)

  # ?????(Datasource) ??
  datasource:
    url: jdbc:h2:mem:testdb  # ???? H2 ?????? ??, ?????? ??? testdb
    # url: jdbc:h2:tcp://localhost/~/testdb # TCP ?? ?? (?? ?? ?? ??)
    # url: jdbc:h2:file:./data/testdb # ?? ?? H2 ?????? ?? (?????? ?? ??? ??? ??)
    driverClassName: org.h2.Driver # H2 ???? ???
    username: sa # H2 ?? ?? ?? (???)
    password:  # H2 ?? ???? (???? ????)

  # JPA (Java Persistence API) ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # H2 ?????? ?? ??
    hibernate:
      ddl-auto: create-drop # ?????? ?? ? ??? ??, ?? ? ??? ?? (???)
      # ddl-auto: update # ??? ??? ???? ?? (???? ??)
      # ddl-auto: validate # ??? ??? ??
      # ddl-auto: none # ??? ?? ??/?? ? ? (???)
    properties:
      hibernate:
        show_sql: true # ???? SQL ??? ??? ??
        format_sql: true # SQL ??? ?? ?? ????? ??
        use_sql_comments: true # SQL ??? ?? ?? (JPA Entity ?? ?)
    defer-datasource-initialization: true # ????? ??? ?? (Spring Boot 2.5 ??)
    # data.sql ?? ????? Hibernate ??? ??? ????? ?
